version: "2.1"
services:
  chronos-mfe:
    image: ${IMAGE_CHRONOS_MFE:-chronos_mfe}
    build:
      context: ../../../packages/chronos-mfe/
      dockerfile: $PWD/chronos-mfe.Dockerfile

  chronos-be:
    image: ${IMAGE_CHRONOS_BE:-chronos_mfe}
    build:
      context: ../../../packages/chronos-backend/
      dockerfile: $PWD/chronos-be.Dockerfile