# Default values for trino.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
appName: trino
namespace: trino
cert:
  certManager: ""
image:
  repository: trinodb/trino
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart version.
  tag: latest

ingress:
  enabled: true
  host: ""
  annotations:
    traefik.frontend.rule.type: PathPrefix
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    cert-manager.io/cluster-issuer: ""
  
server:
  host: ""
  workers: 2
  node:
    environment: production
    dataDir: /data/trino
    pluginDir: /usr/lib/trino/plugin
  log:
    trino:
      level: INFO
  config:
    path: /etc/trino
    internalSharedSecret: 
    http:
      port: 8080
    query:
      maxMemory: "4GB"
      maxMemoryPerNode: "1GB"
    memory:
      heapHeadroomPerNode: "1GB"
  exchangeManager:
    name: "filesystem"
    baseDir: "/tmp/trino-local-file-system-exchange-manager"
  jvm:
    maxHeapSize: "8G"
    gcMethod:
      type: "UseG1GC"
      g1:
        heapRegionSize: "32M"
  autoscaling:
    enabled: false
    maxReplicas: 5
    targetCPUUtilizationPercentage: 50

additionalNodeProperties: {}

additionalJVMConfig: {}

additionalConfigProperties: {}

additionalLogProperties: {}

additionalExchangeManagerProperties: {}

additionalCatalogs: {}

# Array of EnvVar (https://v1-18.docs.kubernetes.io/docs/reference/generated/kubernetes-api/v1.18/#envvar-v1-core)
env: []

initContainers: {}
  # coordinator:
  #   - name: init-coordinator
  #     image: busybox:1.28
  #     imagePullPolicy: IfNotPresent
  #     command: ['sh', '-c', "until nslookup myservice.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for myservice; sleep 2; done"]
  # worker:
  #   - name: init-worker
  #     image: busybox:1.28
  #     command: ['sh', '-c', 'echo The worker is running! && sleep 3600']

securityContext:
  runAsUser: 1000
  runAsGroup: 1000

service:
  type: ClusterIP
  port: 8080

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

serviceAccount:
  # Specifies whether a service account should be created
  create: false
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""
  # Annotations to add to the service account
  annotations: {}

authentication:
  oidc:
    enabled: false
    issuer: ""
    authUrl: ""
    tokenUrl: ""
    jwksUrl: ""
    clientId: ""
    clientSecret: ""
    userInfoUrl: ""
    scopes: "email"
    claim: "sub"
  password:
    user: "immuta"
    bcryptPass: "test"

hivemetastore:
  image: ""
  server:
    session:
      check_interval: "1h"
      timeout: "2h"
    operation:
      timeout: "2h"
    thrift:
      http_timeout: "2h"
  requests:
    memory: "8G"
    cpu: 2
  limits:
    memory: "8G"
    cpu: 2
  minio:
    host: ""
    accessKey: ""
    secretKey: ""
    warehouseBucketName: ""
  postgres:
    host: ""
    db: ""
    user: ""
    password: ""

immuta:
  enabled: false
  name: "immuta"
  endpoint: ""
  apiKey: ""
  listenerName: "immuta-event-listener"
  nonImmutaUserPermission: 