apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-service
  namespace: {{ .Values.namespace }}
  labels:
    name: {{ .Chart.Name }}-service
spec:
  type: ClusterIP
  selector:
    name: {{ .Chart.Name }}
  ports:
    - name: api-http
      protocol: TCP
      port: {{ .Values.containerPort }}
      targetPort: {{ .Values.containerPort }}
