 
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: kong-proxy
  namespace:  {{ template "kong.namespace" . }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: kong
  ingress:
    - ports:
      - port: 8000
        protocol: TCP